#!/usr/bin/env bash
# Sets up everything needed to cross-build this app for x86_64-pc-windows-msvc
# from Linux. Idempotent: re-run it any time, it skips what already exists.
#
#   ./packaging/windows/setup-toolchain.sh
#   source packaging/windows/env.sh      # written by this script
#   cargo xwin build --release --target x86_64-pc-windows-msvc
#
# Nothing here needs Windows, and nothing needs root beyond the apt line below.
set -euo pipefail

ROOT="${OTL_WIN_ROOT:-$HOME/.cache/otl-windows}"
QT_VERSION="5.15.2"
QT_ARCH="win64_msvc2019_64"
script_dir="$(cd "$(dirname "$0")" && pwd)"

echo "==> toolchain root: $ROOT"
mkdir -p "$ROOT"

# 1. Rust target.
rustup target add x86_64-pc-windows-msvc

# 2. cargo-xwin fetches the MSVC CRT + Windows SDK headers/libs from Microsoft.
command -v cargo-xwin >/dev/null || cargo install cargo-xwin

# 3. clang 19+ is REQUIRED. The MSVC STL that xwin downloads carries
#    `#if __clang_major__ < 19 -> #error STL1000`, so clang 18 cannot compile any
#    C++ against it. cargo-xwin auto-creates ~/.cache/cargo-xwin/clang-cl
#    pointing at whatever `clang` it finds and REWRITES IT ON EVERY RUN, so
#    repointing that symlink does not stick — a clang-cl earlier on PATH is the
#    only thing that works.
if [ ! -x /usr/lib/llvm-19/bin/clang ]; then
  echo "!! clang 19 not found. Install it, then re-run:" >&2
  echo "     sudo apt install clang-19 lld-19" >&2
  exit 1
fi
mkdir -p "$ROOT/bin"
for tool in clang lld-link llvm-lib llvm-rc; do
  name="$tool"; [ "$tool" = clang ] && name=clang-cl
  ln -sf "/usr/lib/llvm-19/bin/$tool" "$ROOT/bin/$name"
done

# 4. Qt 5.15.2 built for MSVC. aqtinstall runs on Linux and simply downloads the
#    Windows binaries; 5.15.2 is the last Qt5 with free open-source binaries.
#    qtdeclarative, quickcontrols2, multimedia and sensors are all in the base
#    package for 5.15 — only add-ons like qtcharts are separate modules.
QT_DIR="$ROOT/qt/$QT_VERSION/msvc2019_64"
if [ ! -d "$QT_DIR" ]; then
  # Guard on the binary, not the directory: an interrupted `python3 -m venv`
  # leaves a directory with python symlinks but no pip, and a directory test
  # would then skip creation forever.
  if [ ! -x "$ROOT/aqtenv/bin/aqt" ]; then
    rm -rf "$ROOT/aqtenv"
    python3 -m venv "$ROOT/aqtenv"
    if [ ! -x "$ROOT/aqtenv/bin/pip" ]; then
      echo "!! venv created without pip. Install the venv module, then re-run:" >&2
      echo "     sudo apt install python3-venv" >&2
      exit 1
    fi
    "$ROOT/aqtenv/bin/pip" install -q aqtinstall
  fi
  "$ROOT/aqtenv/bin/aqt" install-qt windows desktop "$QT_VERSION" "$QT_ARCH" -O "$ROOT/qt"
fi

# 5. qmake shim. qttypes 0.2.12 build.rs:221 runs `qmake -query QMAKE_SPEC`
#    unconditionally for any windows target — even when QT_INCLUDE_PATH and
#    QT_LIBRARY_PATH are both set — and panics when qmake is missing. There is no
#    runnable qmake for a Windows Qt on a Linux host, so answer from the known
#    install layout. See WINDOWS-UPSTREAM-ISSUES.md.
#    It must be selected via $QMAKE, not PATH: qmake_query searches
#    qmake6 -> qmake -> qmake-qt5, so a system qmake6 (Qt6, linux-g++) would win
#    over a PATH shim and fail with "not compatible with Qt mkspec 'linux-g++'".
cat > "$ROOT/bin/qmake" <<EOF
#!/usr/bin/env bash
QT_DIR="\${QT_DIR:-$QT_DIR}"
if [ "\$1" = "-query" ]; then
  case "\$2" in
    QMAKE_SPEC|QMAKE_XSPEC) echo "win32-msvc" ;;
    QT_VERSION)             echo "$QT_VERSION" ;;
    QT_INSTALL_HEADERS)     echo "\$QT_DIR/include" ;;
    QT_INSTALL_LIBS)        echo "\$QT_DIR/lib" ;;
    QT_INSTALL_PREFIX)      echo "\$QT_DIR" ;;
    QT_INSTALL_BINS)        echo "\$QT_DIR/bin" ;;
    QT_INSTALL_QML)         echo "\$QT_DIR/qml" ;;
    QT_INSTALL_PLUGINS)     echo "\$QT_DIR/plugins" ;;
    *) echo "" ;;
  esac
  exit 0
fi
echo "qmake shim: unsupported invocation: \$*" >&2
exit 1
EOF
chmod +x "$ROOT/bin/qmake"

# 6. moc runs on the BUILD host, so the Linux Qt5 moc is used rather than running
#    moc.exe under wine. Safe because generated moc code is guarded only on
#    Q_MOC_OUTPUT_REVISION, which is 67 for every Qt 5.15.x — the version string
#    in its #error text is cosmetic. Host and target must stay on the same 5.15.
host_moc=""
for candidate in /usr/lib/qt5/bin/moc /usr/bin/moc; do
  [ -x "$candidate" ] && host_moc="$candidate" && break
done
if [ -z "$host_moc" ]; then
  echo "!! host moc not found. Install it, then re-run:" >&2
  echo "     sudo apt install qtbase5-dev-tools" >&2
  exit 1
fi
host_qt_version="$("$host_moc" --version | awk '{print $2}')"
case "$host_qt_version" in
  5.15.*) ;;
  *) echo "!! host moc is $host_qt_version but the target Qt is $QT_VERSION;" >&2
     echo "   moc output is only portable within the same Qt minor series." >&2
     exit 1 ;;
esac

cat > "$script_dir/env.sh" <<EOF
# Generated by setup-toolchain.sh — source this before cross-building.
export PATH="$ROOT/bin:\$PATH"
export QT_INCLUDE_PATH="$QT_DIR/include"
export QT_LIBRARY_PATH="$QT_DIR/lib"
export QT_MOC="$host_moc"
export QMAKE="$ROOT/bin/qmake"
EOF

echo
clang_version="$("$ROOT/bin/clang-cl" --version | head -1 | awk '{print $4}')"
echo "==> done. clang $clang_version, Qt $QT_VERSION msvc2019_64, host moc $host_qt_version"
echo "    source packaging/windows/env.sh"
echo "    cargo xwin build --release --target x86_64-pc-windows-msvc"
